### ISSUE TITLE
Does not work on my file lss

### ISSUE THREAD

**Issue by JBatHome** [adamzammit/limesurvey-downgrade#1]
I made a file under the cloud version of Limesurvey 6.6.3 and I would like a version 3.23. I'll let you try (file attached in txt format for Github, don't accept ".lss"), personally it sends me an error file.

But really, congratulations on the idea!

All the best,

Jean-Baptiste

[limesurvey_survey_286683.txt](https://github.com/user-attachments/files/16995193/limesurvey_survey_286683.txt)

**Comment by adamzammit** [comment]
Thanks @JBatHome .

There was a bug which has been fixed here: https://github.com/adamzammit/limesurvey-downgrade/commit/c276a9291ffa9ae904125f8a986fd8b710b35a11 - please try again

Adam

**Comment by JBatHome** [comment]
It works! Well done!

Thanks a lot.

Jean-Baptiste
